// 왼쪽   api상의 팀 이름
// 오른쪽 soccerstats상의 팀 이름
var team = {
    epl: [
        ["Manchester United", "Manchester Utd"],
        ["Leicester", "Leicester City"],
        ["Newcastle", "Newcastle Utd"],
        ["Tottenham", "Tottenham"],
        ["Bournemouth", "Bournemouth"],
        ["Liverpool", "Liverpool"],
        ["Norwich", "Norwich City"],
        ["West Ham", "West Ham Utd"],
        ["Manchester City", "Manchester City"],
        ["Sheffield Utd", "Sheffield Utd"],
        ["Burnley", "Burnley"],
        ["Southampton", "Southampton"],
        ["Crystal Palace", "Crystal Palace"],
        ["Everton", "Everton"],
        ["Wolves", "Wolverhampton"],
        ["Watford", "Watford"],
        ["Brighton", "Brighton"],
        ["Aston Villa", "Aston Villa"],
        ["Arsenal", "Arsenal"],
        ["Chelsea", "Chelsea"]
        ],
    bundesliga: [
        ["Bayern Munich", "Bayern Munich"],
        ["Hertha Berlin", "Hertha Berlin"],
        ["Borussia Dortmund", "Dortmund"],
        ["FC Augsburg", "FC Augsburg"],
        ["Bayer Leverkusen", "Leverkusen"],
        ["SC Paderborn 07", "Paderborn"],
        ["VfL Wolfsburg", "Wolfsburg"],
        ["FC Koln", "FC Koln"],
        ["Werder Bremen", "Werder Bremen"],
        ["Fortuna Dusseldorf", "Dusseldorf"],
        ["SC Freiburg", "Freiburg"],
        ["FSV Mainz 05", "FSV Mainz"],
        ["Borussia Monchengladbach", "Monchengladbach"],
        ["FC Schalke 04", "Schalke 04"],
        ["Eintracht Frankfurt", "E. Frankfurt"],
        ["1899 Hoffenheim", "Hoffenheim"],
        ["Union Berlin", "Union Berlin"],
        ["RB Leipzig", "RB Leipzig"]
    ],
    laliga: [
        ["Athletic Club", "Athletic Bilbao"],
        ["Barcelona", "FC Barcelona"],
        ["Celta Vigo", "Celta Vigo"],
        ["Real Madrid", "Real Madrid"],
        ["Valencia", "Valencia"],
        ["Real Sociedad", "Real Sociedad"],
        ["Leganes", "Leganes"],
        ["Osasuna", "Osasuna"],
        ["Villarreal", "Villarreal"],
        ["Granada CF", "Granada"],
        ["Alaves", "Alaves"],
        ["Levante", "Levante"]
        ["Espanyol", "Espanyol"],
        ["Sevilla", "FC Sevilla"],
        ["Atletico Madrid", "Atletico Madrid"],
        ["Getafe", "Getafe"],
        ["Mallorca", "Mallorca"],
        ["Eibar", "Eibar"],
        ["Real Betis", "Real Betis"],
        ["Valladolid", "Valladolid"]
    ],
    seiea: [
        ["Cagliari", "Cagliari"],
        ["Brescia", "Brescia"],
        ["Fiorentina", "Fiorentina"],
        ["Napoli", "Napoli"],
        ["Verona", "Hellas Verona"],
        ["Bologna", "Bologna"],
        ["Inter", "Inter Milan"],
        ["Lecce", "Lecce"],
        ["Parma", "Parma"],
        ["Juventus", "Juventus"],
        ["AS Roma", "AS Roma"],
        ["Genoa", "Genoa"],
        ["Sampdoria", "Sampdoria"],
        ["Lazio", "Lazio"],
        ["Spal", "SPAL"],
        ["Atlanta", "Atlanta"],
        ["Torino", "Torino"],
        ["Sassuolo", "Sassuolo"],
        ["Udinese", "Udinese"],
        ["AC Milan", "AC Milan"],
    ],
    ligue1:[
        ["Dijon","Dijon"],
        ["Saint Etienne","Saint-Etienne"],
        ["Marseille","Marseille"],
        ["Reims","Reims"],
        ["Nice","Nice"],
        ["Amiens","Amiens"],
        ["Strasbourg","Strasbourg"],
        ["Metz","Metz"],
        ["Montpellier","Montpellier"],
        ["Rennes","Rennes"],
        ["Angers","Angers"],
        ["Bordeaux","Bordeaux"],
        ["Lille","Lille"],
        ["Nantes","Nantes"],
        ["Paris Saint Germain","Paris SG"],
        ["Nimes","Nimes"],
        ["Stade Brestois 29","Brest"],
        ["Toulouse","Toulouse"],
        ["Monaco","Monaco"],
        ["Lyon","Lyon"]
    ],
    eredivisie:[
        ["Ajax","Ajax Amsterdam"],
        ["AZ Alkmaar","AZ Alkmaar"],
        ["PSV Eindhoven","PSV Eindhoven"],
        ["Utrecht","FC Utrecht"],
        ["Vitesse","Vitesse Arnhem"],
        ["Willem II","Willem II"],
        ["Heracles","Heracles Almelo"],
        ["Heerenveen","Heerenveen"],
        ["Groningen","FC Groningen"],
        ["Feyenoord","Feyenoord"],
        ["Emmen","FC Emmen"],
        ["Fortuna Sittard","Fortuna Sittard"],
        ["ADO Den Haag","ADO Den Haag"],
        ["PEC Zwolle","PEC Zwolle"],
        ["VVV Venlo","VVV"],
        ["Wallwijk","RKC Waalwijk"]
    ]
};

module.exports = team;
